import Head from 'next/head'
import MainLayout from '../components/layouts/Main'
export default function Home() {
  return (
    <>

      <Head>
        <title>Appiewerken</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    	 <MainLayout>

       <h1 className="text-2xl font-bold text-sky-500">Index</h1>
         
       </MainLayout>
       
    
    </>
  )
}
